version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    restart: always

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
